# Generated by Django 3.2.6 on 2023-05-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='name',
            field=models.CharField(default='Nick Langat', max_length=250),
            preserve_default=False,
        ),
    ]
